services:
  - type: web
    name: tottal-analise-api
    env: docker
    plan: free
    # buildCommand and startCommand are not needed for Docker, 
    # Render uses the Dockerfile CMD.

    envVars:
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
